dataset:
  root: ./data/real/objects_1211
  clip: 768
  size: 32
  background: 0
  target_size: 32
  color: g

split: 1cm_768x32x32

rsd:
  t: 768
  d: 64
  h: 32
  w: 32
  in_plane: 1
  wall_size: 2
  bin_len: 0.01
  zmin: 0.5
  zmax: 2.5
  scale_coef: 1
  n_cycles: 4
  ratio: 0.1
  actv: linear
  norm: none

batch_size: 1
n_workers: 12