dataset:
  root: ./data/real/objects_1211
  clip: 384
  size: 192
  background: 0
  target_size: 192
  color: g

split: 2cm_384x192x192

rsd:
  t: 384
  d: 64
  h: 192
  w: 192
  in_plane: 1
  wall_size: 2
  bin_len: 0.02
  zmin: 0.5
  zmax: 2.5
  scale_coef: 3
  n_cycles: 4
  ratio: 0.1
  actv: linear
  norm: none

batch_size: 1
n_workers: 12