dataset:
  root: ./data/synthetic/letters
  clip: 512
  size: 128
  background: 0
  target_size: 128
  color: gray

split: val_unseen_objs_128

rsd:
  t: 512
  d: 64
  h: 128
  w: 128
  in_plane: 1
  wall_size: 2
  bin_len: 0.01
  zmin: 0
  zmax: 2
  scale_coef: 2
  n_cycles: 4
  ratio: 0.1
  actv: linear
  norm: none

batch_size: 1
n_workers: 12