dataset:
  path: ./data/real/objects_1211/num24/num24_2/meas/processed/1cm_768x32x32.mat
  clip: 768
  scale: 1
  background: 0
  color: g

rsd:
  t: 768
  d: 32
  h: 32
  w: 32
  in_plane: 1
  wall_size: 2
  bin_len: 0.01
  zmin: 0.8
  zmax: 1.8
  scale_coef: 1
  n_cycles: 4
  ratio: 0.1
  actv: linear
  norm: none