meas:
  path: ./data/synthetic/per_scene/letters/1cm_600x128x128.hdr
  clip: 512
  size: 128
  scale: 1
  background: [0.05, 0.2]
  color: g

target:
  path: ./data/synthetic/per_scene/letters/brightness.hdr
  target_size: 128
  color: g

camera:
  type: orthographic

  orthographic:
    size: 2
    res: 128

wall:
  size: 2
  res: 128
  block_size: 128
  uv_size: 64
  foreshortening: False
  depth: 0.5

model:
  embedder:
    embed_p: true
    embed_d: true
    embed_z: false
    p:
      in_dim: 3
      include_input: true
      n_freqs: 6 # 10
    d:
      in_dim: 2
      include_input: false
      n_freqs: 4
    z:
      in_dim: null

  field:
    type: nerf

    nerf:
      hid_dim: 128
      color_dim: 1
      skips: !!python/list [5]
      n_sigma_layers: 8
      n_color_layers: 1
      actv: relu

  common:
    bb_ctr: !!python/list [0, 0, 0.25]
    bb_size: !!python/list [2, 2, 1.5]
    inf: 10
    p_polar: false
    d_polar: true
    z_norm: false
    sigma_transform: relu
    color_transform: relu

  steady_state:
    bin_len: 0.02
    n_bins: 128

  transient:
    light: !!python/list [0, 0, -1]
    bin_range: !!python/list [128, 512]
    bin_len: 0.01

opt:
  n_itrs: 100000

  optim_type: adam
  lr: 1.e-4
  weight_decay: 0.0
  beta1: 0.9
  beta2: 0.999

  clip_grad_norm: 1.0

  sched_type: step
  milestones: [-1]
  gamma: 0.1

  poisson: 1
  beta: 0 # 1.e-4
  tv: 0 # 0.1

train:
  n_steps: 1
  t_scale: 25465
  sigma_noise: 0
  color_noise: 0
  bin_range: [128, 512]

eval:
  n_views: 1
  include_orthogonal: true
  chunk_size: 4096
  normalize: true # false

  n_steps: 2
  s_scale: 1
  sigma_noise: 0
  color_noise: 0