# 16GB GPU * 2 (euler20)

dataset:
  root: ./data/synthetic/bikes
  clip: 512
  size: 128
  background: [0.05, 0.2]
  target_size: 128
  color: rgb

splits:
  train: train_128
  val: val_unseen_poses_128

camera:
  type: orthographic

  orthographic:
    size: 2
    res: 128

wall:
  size: 2
  res: 128
  block_size: 128
  uv_size: 64
  foreshortening: False
  depth: 0.5

model:
  encoder:
    type: rsdnet

    rsdnet:
      in_plane: 3
      plane: 16
      in_block: true
      ds: true

      rsd:
        t: 256
        d: 32
        h: 64
        w: 64
        in_plane: 16
        wall_size: 2
        bin_len: 0.02
        zmin: 0.5
        zmax: 1.5
        scale_coef: 1

      actv: leaky_relu
      norm: none
      affine: false

  renderer:
    embedder:
      embed_p: true
      embed_d: true
      embed_z: false
      p:
        in_dim: 3
        include_input: true
        n_freqs: 6 # 10
      d:
        in_dim: 2
        include_input: false
        n_freqs: 4
      z:
        in_dim: 16

    field:
      type: nerf

      nerf:
        hid_dim: 64 # 32
        color_dim: 3
        skips: !!python/list []
        n_sigma_layers: 2
        n_color_layers: 1
        actv: relu
        film_hid_dim: 32
        film_n_layers: 2
        film_actv: leaky_relu

    common:
      bb_ctr: !!python/list [0, 0, 0]
      bb_size: !!python/list [2, 2, 1]
      inf: 10
      p_polar: false
      d_polar: true
      z_norm: false
      sigma_transform: relu
      color_transform: relu

    steady_state:
      bin_len: 0.02
      n_bins: 128

    transient:
      light: !!python/list [0, 0, -1]
      bin_range: !!python/list [128, 384]
      bin_len: 0.01

opt:
  batch_size: 2
  n_workers: 32
  n_itrs: 200000

  optim_type: adam
  lr: 1.e-4
  weight_decay: 0.0
  beta1: 0.9
  beta2: 0.999

  clip_grad_norm: 1.0

  sched_type: step
  milestones: [-1]
  gamma: 0.1

  poisson: 1
  beta: 1.e-4
  tv: 0 # 0.1

train:
  n_steps: 1
  in_scale: 1
  t_scale: 25465
  sigma_noise: 0  # 1
  color_noise: 0
  bin_range: [128, 384]

eval:
  n_views: 1
  include_orthogonal: true
  chunk_size: 4096
  normalize: true # false

  n_steps: 2
  in_scale: 1
  s_scale: 1
  sigma_noise: 0
  color_noise: 0