dataset:
  root: ./data/synthetic/bikes  # ./data/real/objects_1211
  scale: 1
  ds: 1
  clip: 512
  size: 256
  background: 0
  target_size: 256
  color: rgb

split: val_unseen_objs_256  # 1cm_768x256x256

eval:
  n_views: 1
  include_orthogonal: true
  in_scale: null

batch_size: 1
n_workers: 12