dataset:
  root: ./data/synthetic/bikes
  scale: 1
  ds: 1
  clip: 512
  size: 128
  background: [0.05, 0.2]
  target_size: 128
  target_noise: 0.005
  color: rgb

splits:
  train: train_128
  val: val_unseen_poses_128

model:
  encoder:
    type: ffc

    ffc:
      t: 512
      d: 64
      h: 128
      w: 128
      in_plane: 3
      plane: 512
      out_plane: 8
      n_layers: 5
      bottleneck: true
      expansion: 4
      actv: relu
      norm: batch
      affine: true
      pe: false

  decoder:
    transformer:
      d: 64
      h: 64
      w: 64
      wall_size: 2
      zmin: -1
      zmax: 1

    renderer:
      type: v2

      v2:
        in_plane: 8
        out_plane: 3
        min_plane: 4
        actv: leaky_relu
        norm: none
        affine: false

opt:
  batch_size: 2
  n_workers: 12
  n_itrs: 125000

  optim_type: adam
  lr: 1.e-4
  momentum: 0.9
  weight_decay: 0.0
  beta1: 0.9
  beta2: 0.999

  clip_grad_norm: 1.0

  sched_type: step
  milestones: [125000]
  gamma: 0.1

train:
  n_views: 4
  include_orthogonal: true
  in_scale: 1

eval:
  n_views: 1
  include_orthogonal: true
  in_scale: 1